#!/bin/bash

set -euo pipefail

CONFIG_FILE="${SIGNING_CONFIG_FILE:-.voform-signing-identity}"
REQUESTED_IDENTITY="${SIGN_IDENTITY:-}"
FORCE_SELECTION="${FORCE_SIGNING_IDENTITY_SELECTION:-0}"

declare -a IDENTITY_HASHES=()
declare -a IDENTITY_NAMES=()

log() {
    printf '%s\n' "$*" >&2
}

certificate_is_self_signed() {
    local name="$1"
    local certificate subject issuer

    certificate="$(security find-certificate -c "$name" -p 2>/dev/null || true)"
    [[ -n "$certificate" ]] || return 1

    subject="$(printf '%s' "$certificate" | openssl x509 -noout -subject -nameopt RFC2253 2>/dev/null | sed 's/^subject=//')"
    issuer="$(printf '%s' "$certificate" | openssl x509 -noout -issuer -nameopt RFC2253 2>/dev/null | sed 's/^issuer=//')"
    [[ -n "$subject" && "$subject" == "$issuer" ]]
}

scan_identities() {
    local line hash name
    while IFS= read -r line; do
        if [[ "$line" == *"CSSMERR_"* || "$line" == *"REVOKED"* ]]; then
            continue
        fi
        if [[ "$line" =~ \)[[:space:]]+([0-9A-Fa-f]{40})[[:space:]]+\"(.*)\" ]]; then
            hash="${BASH_REMATCH[1]}"
            name="${BASH_REMATCH[2]}"
            if certificate_is_self_signed "$name"; then
                IDENTITY_HASHES+=("$hash")
                IDENTITY_NAMES+=("$name")
            fi
        fi
    done < <(security find-identity -v -p codesigning 2>/dev/null || true)
}

find_candidate() {
    local requested="$1"
    local index
    for ((index = 0; index < ${#IDENTITY_HASHES[@]}; index++)); do
        if [[ "${IDENTITY_HASHES[$index]}" == "$requested" || "${IDENTITY_NAMES[$index]}" == "$requested" ]]; then
            printf '%s' "$index"
            return 0
        fi
    done
    return 1
}

save_candidate() {
    local index="$1"
    local temporary_file="${CONFIG_FILE}.tmp.$$"

    umask 077
    {
        printf '# Generated by Scripts/resolve-signing-identity.sh; intentionally gitignored.\n'
        printf 'identity_sha1=%s\n' "${IDENTITY_HASHES[$index]}"
        printf 'identity_name=%s\n' "${IDENTITY_NAMES[$index]}"
    } > "$temporary_file"
    mv "$temporary_file" "$CONFIG_FILE"
}

print_no_identity_help() {
    log "No usable self-signed Code Signing identity was found in the keychains."
    log ""
    log "Create one in Keychain Access:"
    log "  1. Keychain Access > Certificate Assistant > Create a Certificate…"
    log "  2. Choose Identity Type: Self Signed Root"
    log "  3. Choose Certificate Type: Code Signing"
    log "  4. Store it in the login keychain and ensure its private key appears beneath it"
    log "  5. Set the certificate's Code Signing trust to Always Trust if macOS requests it"
    log ""
    log "Verify it with: security find-identity -v -p codesigning"
    log "Then run: make signing-identity"
}

scan_identities

if [[ ${#IDENTITY_HASHES[@]} -eq 0 ]]; then
    print_no_identity_help
    exit 2
fi

selected_index=""

if [[ -n "$REQUESTED_IDENTITY" ]]; then
    if ! selected_index="$(find_candidate "$REQUESTED_IDENTITY")"; then
        log "SIGN_IDENTITY does not match an available self-signed Code Signing identity: $REQUESTED_IDENTITY"
        exit 2
    fi
elif [[ "$FORCE_SELECTION" != "1" && -f "$CONFIG_FILE" ]]; then
    saved_hash="$(sed -n 's/^identity_sha1=//p' "$CONFIG_FILE" | head -n 1)"
    if [[ -n "$saved_hash" ]]; then
        selected_index="$(find_candidate "$saved_hash" || true)"
        if [[ -z "$selected_index" ]]; then
            log "The identity saved in $CONFIG_FILE is no longer available; selecting again."
        fi
    fi
fi

if [[ -z "$selected_index" && ${#IDENTITY_HASHES[@]} -eq 1 ]]; then
    selected_index=0
    log "Using the only available self-signed Code Signing identity: ${IDENTITY_NAMES[0]}"
fi

if [[ -z "$selected_index" ]]; then
    log "Available self-signed Code Signing identities:"
    for ((index = 0; index < ${#IDENTITY_HASHES[@]}; index++)); do
        log "  $((index + 1))) ${IDENTITY_NAMES[$index]} [${IDENTITY_HASHES[$index]}]"
    done

    if [[ ! -r /dev/tty || ! -w /dev/tty ]]; then
        log "No interactive terminal is available. Re-run with SIGN_IDENTITY='<name-or-SHA1>'."
        exit 2
    fi

    while true; do
        printf 'Select a signing identity [1-%d]: ' "${#IDENTITY_HASHES[@]}" > /dev/tty
        IFS= read -r selection < /dev/tty
        if [[ "$selection" =~ ^[0-9]+$ ]] && ((selection >= 1 && selection <= ${#IDENTITY_HASHES[@]})); then
            selected_index=$((selection - 1))
            break
        fi
        log "Invalid selection."
    done
fi

save_candidate "$selected_index"
log "Signing identity: ${IDENTITY_NAMES[$selected_index]}"
log "Saved selection to $CONFIG_FILE"
printf '%s\n' "${IDENTITY_HASHES[$selected_index]}"
